import {
  valentino_finest1,
  vodka_finest,
  valentino_finest3,
  valentino_finest4,
  valentino_finest5,
  valentino_finest6,
  valentino_finest7,
  valentino_finest8,
  valentino_finest9,
  valentino_finest10,
  valentino_finest11,
  valentino_finest12,
  valentino_finest13,
  valentino_finest14,
  valentino_finest15,
} from "../../assets/index";

const ProductPrototype = [
  {
    name: "Valentino Original",
    category: "BEER",
    description: "Description for Valentino",
    id: 1,
    imageURL: valentino_finest1,
    isAvailable: true,
    brand: "Valentino Original",
    price: "$120",
    quantity: 10,
  },

  {
    name: "Vodka Finest",
    category: "RUM",
    description: "Description for Vodka Finest",
    id: 2,
    imageURL: vodka_finest,
    isAvailable: true,
    brand: "Vodka Finest",
    price: "$130",
    quantity: 10,
  },
  {
    name: "Valentino Finest",
    category: "RUM",
    description: "Description for Valentino Finest",
    id: 3,
    imageURL: valentino_finest3,
    isAvailable: true,
    brand: "Valentino Finest",
    price: "$140",
    quantity: 10,
  },
  {
    name: "Martell",
    category: "RUM",
    description: "Description for Martell",
    id: 4,
    imageURL: valentino_finest4,
    isAvailable: true,
    brand: "Martell",
    price: "$150",
    quantity: 10,
  },
  {
    name: "St'Laurens",
    category: "WINE",
    description: "Description for St'Laurens",
    id: 5,
    imageURL: valentino_finest5,
    isAvailable: true,
    brand: "St'Laurens",
    price: "$110",
    quantity: 10,
  },
  {
    name: "Ginger Beer",
    category: "BEER",
    description: "Description for Ginger Beer",
    id: 6,
    imageURL: valentino_finest6,
    isAvailable: true,
    brand: "Ginger Beer",
    price: "$130",
    quantity: 10,
  },
  {
    name: "Heineken",
    category: "BEER",
    description: "Description for Heineken",
    id: 7,
    imageURL: valentino_finest7,
    isAvailable: true,
    brand: "Heineken",
    price: "$170",
    quantity: 10,
  },
  {
    name: "Bailey's",
    category: "RUM",
    description: "Description for Bailey's",
    id: 8,
    imageURL: valentino_finest8,
    isAvailable: true,
    brand: "Bailey's",
    price: "$170",
    quantity: 10,
  },

  {
    name: "Guinness",
    category: "BEER",
    description: "Description for Guinness",
    id: 9,
    imageURL: valentino_finest9,
    isAvailable: true,
    brand: "Guinness",
    price: "$190",
    quantity: 10,
  },

  {
    name: "ESpJaerd Vodka",
    category: "VODKA",
    description: "Description for ESpJaerd Vodka",
    id: 10,
    imageURL: valentino_finest10,
    isAvailable: true,
    brand: "ESpJaerd Vodka",
    price: "$120",
    quantity: 10,
  },

  {
    name: "Four Brother's",
    category: "WHISKEY",
    description: "Description for Four Brother's",
    id: 11,
    imageURL: valentino_finest11,
    isAvailable: true,
    brand: "Four Brother's",
    price: "$130",
    quantity: 10,
  },

  {
    name: "Centurion's",
    category: "WHISKEY",
    description: "Description for Centurion's",
    id: 12,
    imageURL: valentino_finest12,
    isAvailable: true,
    brand: "Centurion's",
    price: "$180",
    quantity: 10,
  },
  {
    name: "Jose Cuervo's Special",
    category: "RUM",
    description: "Description for Jose Cuervo's Special",
    id: 13,
    imageURL: valentino_finest13,
    isAvailable: true,
    brand: "Jose Cuervo's Special",
    price: "$170",
    quantity: 10,
  },
  {
    name: "ESpJaerd Cocktail",
    category: "COCKTAIL",
    description: "Description for ESpJaerd Cocktail",
    id: 14,
    imageURL: valentino_finest14,
    isAvailable: true,
    brand: "ESpJaerd Cocktail",
    price: "$190",
    quantity: 10,
  },

  {
    name: "White Wine",
    category: "RUM",
    description: "Description for White Wine",
    id: 15,
    imageURL: valentino_finest15,
    isAvailable: true,
    brand: "White Wine",
    price: "$120",
    quantity: 10,
  },
];

export default ProductPrototype;
